<?php
function votesmart_webform_menu()
{
  $items = array();

  // Admin Settings.
  $items['admin/settings/votesmart_webform'] = array(
    'title' => 'Vote Smart Webform',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('votesmart_webform_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'description' => 'Configuration for Vote Smart webform.',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/settings/votesmart_webform/flush_candidates'] = array(
    'title' => 'Flush Candidate Data',
    'page callback' => 'votesmart_webform_flush_candidates',
    'access arguments' => array('administer site configuration'),
    'description' => 'Flush Candidate Data - data will be refreshed via Vote Smart API when needed.',
    'type' => MENU_NORMAL_ITEM
  );

  $items['votesmart_webform/ahah/get_candidates'] = array(
    'title' => 'AHAH Callback for Vote Smart Webform',
    'page callback' => 'votesmart_webform_ahah_get_candidates',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'votesmart_webform.webform.inc'
  );

  return $items;
}

function votesmart_webform_flush_candidates()
{
  //truncate is a non standard SQL command :(
  db_query('DELETE FROM {votesmart_webform_candidates}');
  db_query('DELETE FROM {votesmart_webform_cached_queries}');
  $msg = '<h3>'.t('Vote Smart candidate data has been flushed').'</h3>';
  $msg .= '<p>'.t('This data will be refreshed by the Vote Smart API when it is needed again').'</p>';
  drupal_set_message($msg); 
  return '';
}

function votesmart_webform_webform_component_info() {
  //component was originally called votesmart_webform,
  //but it was too long? m got chopped off.
  return array('votesmart' => array(
    'type' => 'email',
    'label' => t('Vote Smart Lookup'),
    'description' => t('Looks up Representative for Given Zip Code'),
    'features' => array(
      'csv' => FALSE,
      'email' => FALSE,
      'required' => TRUE,
      'conditonal' => FALSE,
    ),
    'file' => 'votesmart_webform.webform.inc'
  ));
}

/**
 * Uses same settings and keys as votesmart module
 */
function votesmart_webform_admin_settings() {
  $form = array();
  $form['api'] = array(
    '#type' => 'fieldset',
    '#title' => ('API Settings')
  );
  $form['api']['votesmart_host'] = array(
    '#type' => 'textfield',
    '#title' => t('Votesmart API server'),
    '#description' => t(''),
    '#default_value' => variable_get('votesmart_host', 'http://api.votesmart.org/'),
  );
  $form['api']['votesmart_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Votesmart API key'),
    '#description' => '<a href="http://www.votesmart.org/user_register.php">'.t('Register for Key').'</a>',
    '#default_value' => variable_get('votesmart_key', ''),
  );

  return system_settings_form($form);
}

/**
 * Same Request function used by votesmart module
 */
function _votesmart_webform_api($request, $args = array(), $item = null) {
  $key = variable_get('votesmart_key', '');
  $url = variable_get('votesmart_host', 'http://api.votesmart.org/');

  // Convert arguments into a request string.
  $args = array_merge($args, array('key' => $key));
  $url .= $request . '?';
  foreach ($args as $k => $v) {
    $url .= check_plain($k) . '=' . check_plain($v) . '&';
  }

  // Contact the REST API.
  $res = drupal_http_request($url);
  $ret = (array) new SimpleXMLElement($res->data, LIBXML_NOCDATA);

  /*
  if (isset($ret['errorMessage'])) {
    drupal_set_message(t('Vote Smart API error: %err', array('%err' => $ret['errorMessage'])), 'error');
  }
  */

  // Return specified element (e.g. 'details', 'list', etc.);
  if ($item) {
    foreach (explode('.', $item) as $key) {
      $ret = (array) $ret[$key];
    }
  }

  // Nothing specified, return the entire object.
  return $ret;
}

function votesmart_webform_is_us_state($state_abbr)
{
  include('votesmart_webform.defines.php');
  return isset($VOTESMART_WEBFORM_US_STATES[$state_abbr]);
}

//office types and ids are the same,
//keeping language the same as votesmart api
function votesmart_webform_is_office_id($officeId)
{
  include('votesmart_webform.defines.php');
  return isset($VOTESMART_WEBFORM_OFFICE_TYPES[$officeId]);
}


function votesmart_webform_is_zip($zip)
{
  return preg_match('/^[0-9]{5}([- ]?[0-9]{4})?$/', $zip);
}



function votesmart_webform_get_candidate($candidateId, $partial_candidate_xml = NULL, $full = true)
{
  $candidateId.='';//convert to string

  static $candidates;//cache candidates
  
  if( !isset($candidates) )
    $candidates = array();

  if( !isset($candidates[$candidateId]) )
  {
    $c = array();//candidate array

    //only hit the database if we need more than the name
    //or haven't been provided any info
    if( $full || empty($partial_candidate_xml))
      $candidate_data = db_result(db_query('SELECT data FROM {votesmart_webform_candidates} WHERE candidate_id = %d LIMIT 1',array($candidateId)));
    if( $candidate_data )
    {
      $c = unserialize($candidate_data);
    }
    else
    {
      //not scoped so we have opportunity to fix candidate name
      //if it is missing from partial $partial_candidate_xml

      if( $full )
      {
        $c_xml_web = _votesmart_webform_api('Address.getOfficeWebAddress',array('candidateId'=>$candidateId));
        $c_xml_addr = _votesmart_webform_api('Address.getOffice',array('candidateId'=>$candidateId),'office');
      }

      //officials can have multiple offices listed,
      //we are only saving the first one
      if( isset($c_xml_addr[0]->address) )
      {
        foreach($c_xml_addr[0]->address as $k => $v)
        {
          $v = trim($v);
          if( !empty($v) )
            $c['address'][$k] = $v;
        }
      }

			$vars_to_save = array(
        'title',
        'firstName',
        'middleName',
        'lastName',
        'suffix',
			  'nickName',
        'officeTypeId',
        'officeName'
			);

      foreach($vars_to_save as $var)
      {
				if( !empty($c_xml_web['candidate']->$var) )
          $c[$var] = $c_xml_web['candidate']->$var.'';
        else if( !empty($partial_candidate_xml->$var) )
          $c[$var] = $partial_candidate_xml->$var.'';
      }

      if( is_array($c_xml_web['address']) )
        foreach($c_xml_web['address'] as $addr)
          $c[$addr->webAddressType.''] = $addr->webAddress.'';

      if( empty($c) ) return false;

      if( $full )
        @db_query('INSERT INTO {votesmart_webform_candidates} (candidate_id, data) values (%d,\'%s\')',$candidateId,serialize($c));
    }

    $candidates[$candidateId] = $c;
  }

  return $candidates[$candidateId];
}

function votesmart_webform_get_candidates($args)
{
  $args['zip'] = preg_replace('@[^\d]@','',$args['zip']);//strip non digits

  $query_key = serialize($args);

  $cached_query = db_result(db_query('SELECT response FROM {votesmart_webform_cached_queries} WHERE query = \'%s\'',$query_key));
  if( $cached_query )
  {
    return unserialize($cached_query);
    /*
    $candidates = array();
    $cand_ids = explode(';',$cached_query);
    foreach($cand_ids as $id)
    {
      $candidate = votesmart_webform_get_candidate($id);
      if( $candidate && ( !empty($candidate['Email']) || !empty($candidate['address']) ) )
        $candidates[$id] = $candidate;
    }
    return $candidates;
    */
  }

  $zip = $args['zip'];
  $state = $args['state'];
  $officeId = $args['officeId'];
  $full = $args['full'];

  $args = array();//set this to empty array as it is used later

  if( votesmart_webform_is_zip($zip) )
  {

    $args = array('zip5' => substr($zip,0,5) );
    if( strlen($zip) == 9 )
      $args['zip4'] = substr($zip,5,9);
  
    $candidates = _votesmart_webform_api('Officials.getByZip',$args,'candidate');
  }
  else if( votesmart_webform_is_us_state($state) )
  {
    if( isset($officeId) && !votesmart_webform_is_office_id($officeId) )
      $officeId = NULL;

    $args = array('stateId' => $state );
    if( isset($officeId) && votesmart_webform_is_office_id($officeId) )
      $args['officeId'] = $officeId;

    if( isset($args['officeId']) )
      $candidates = _votesmart_webform_api('Officials.getByOfficeState',$args,'candidate');
    else
      $candidates = _votesmart_webform_api('Officials.getStatewide',$args,'candidate');
      
  }
  else return array();

  $sanitized_candidates = array();
	
  if( is_array($candidates) )
  {
    foreach($candidates as $c)
    {
      $candidate = votesmart_webform_get_candidate($c->candidateId,$c,$full);
      if( !empty($candidate) )
        $sanitized_candidates[$c->candidateId.''] = $candidate;
    }
  }


  db_query('INSERT INTO {votesmart_webform_cached_queries} (query,response) values (\'%s\',\'%s\')',$query_key,serialize($sanitized_candidates));
  //db_query('INSERT INTO {votesmart_webform_cached_queries} (query,response) values (\'%s\',\'%s\')',$query_key,implode(';',array_keys($sanitized_candidates)));
  return $sanitized_candidates;
}

