<?php
/*
$VS_WEBFORM_OFFICE_TYPES = array(
  'P' => array('name'=> 'Presidential and Cabinet', 'level' => 'F','branch' => 'E'),
  'C' => array('name'=> 'Congressional',            'level' => 'F','branch' => 'L'),
  'J' => array('name'=> 'Supreme Court',            'level' => 'F','branch' => 'J'),
  'G' => array('name'=> 'Governor and Cabinet',     'level' => 'S','branch' => 'E'),
  'K' => array('name'=> 'State Judicial',           'level' => 'S','branch' => 'J'),
  'L' => array('name'=> 'State Legislature',        'level' => 'S','branch' => 'L'),
  'S' => array('name'=> 'State Wide',               'level' => 'L','branch' => 'E'),
  'H' => array('name'=> 'Local Judicial',           'level' => 'L','branch' => 'J'),
  'N' => array('name'=> 'Local Legislative',        'level' => 'L','branch' => 'L'),
  'M' => array('name'=> 'Local Executive',          'level' => 'L','branch' => 'E'),
);*/
$VS_WEBFORM_OFFICE_TYPES = array(
  'P' => 'Presidential and Cabinet', //'level' => 'F','branch' => 'E'),
  'C' => 'Congressional',            //'level' => 'F','branch' => 'L'),
  'J' => 'Supreme Court',            //'level' => 'F','branch' => 'J'),
  'G' => 'Governor and Cabinet',     //'level' => 'S','branch' => 'E'),
  'K' => 'State Judicial',           //'level' => 'S','branch' => 'J'),
  'L' => 'State Legislature',        //'level' => 'S','branch' => 'L'),
  'S' => 'State Wide',               //'level' => 'L','branch' => 'E'),
  'H' => 'Local Judicial',           //'level' => 'L','branch' => 'J'),
  'N' => 'Local Legislative',        //'level' => 'L','branch' => 'L'),
  'M' => 'Local Executive',          //'level' => 'L','branch' => 'E'),
);

$VS_WEBFORM_OFFICE_BRANCHES = array('E' => 'Executive','L'=> 'Legislative', 'J' => 'Judicial');
$VS_WEBFORM_OFFICE_LEVELS = array('F' => 'Federal', 'S' => 'State', 'L' => 'Local');
$VS_WEBFORM_US_STATES = array('AL'=>'Alabama', 'AK'=>'Alaska', 'AZ'=>'Arizona', 'AR'=>'Arkansas', 'CA'=>'California', 'CO'=>'Colorado', 'CT'=>'Connecticut', 'DE'=>'Delaware', 'DC'=>'District of Columbia', 'FL'=>'Florida', 'GA'=>'Georgia', 'HI'=>'Hawaii', 'ID'=>'Idaho', 'IL'=>'Illinois', 'IN'=>'Indiana', 'IA'=>'Iowa', 'KS'=>'Kansas', 'KY'=>'Kentucky', 'LA'=>'Louisiana', 'ME'=>'Maine', 'MD'=>'Maryland', 'MA'=>'Massachusetts', 'MI'=>'Michigan', 'MN'=>'Minnesota', 'MS'=>'Mississippi', 'MO'=>'Missouri', 'MT'=>'Montana', 'NE'=>'Nebraska', 'NV'=>'Nevada', 'NH'=>'New Hampshire', 'NJ'=>'New Jersey', 'NM'=>'New Mexico', 'NY'=>'New York', 'NC'=>'North Carolina', 'ND'=>'North Dakota', 'OH'=>'Ohio', 'OK'=>'Oklahoma', 'OR'=>'Oregon', 'PA'=>'Pennsylvania', 'RI'=>'Rhode Island', 'SC'=>'South Carolina', 'SD'=>'South Dakota', 'TN'=>'Tennessee', 'TX'=>'Texas', 'UT'=>'Utah', 'VT'=>'Vermont', 'VA'=>'Virginia', 'WA'=>'Washington', 'WV'=>'West Virginia', 'WI'=>'Wisconsin', 'WY'=>'Wyoming');
